# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: "WONISM"
subtitle:
description: "wonism's blog"
author: wonism
language: en
timezone: ROK

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://wonism.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

menu:
    Home: /
    # Delete this row if you don't want categories in your header nav bar
    # Categories:
    About: https://about.me/jaewonism
    GitHub: https://github.com/wonism

customize:
  logo:
    width: 140
    height: 60
    url: https://jaewonism.cf/images/new_logo_white.png
  theme_color: '#3b8dbd'
  highlight: darkula
  sidebar: left
  thumbnail: false # enable posts thumbnail, options: true, false
  favicon: https://jaewonism.cf/favicon.ico # path to favicon
  social_links: # for more icons, please see http://fontawesome.io/icons/#brand
    facebook: https://www.facebook.com/j1.chic
    instagram: https://www.instagram.com/1000000000000._.won/
    github: https://github.com/wonism
    rss: https://wonism.github.io/atom.xml

# Widgets
widgets:
  - recent_posts
  - archive
  - tag
  - tagcloud

# Disqus
comment:
  disqus: jaewonism
  duoshuo:
  youyan:

# Search
search:
  insight: true # you need to install `hexo-generator-json-content` before using Insight Search
  swiftype: # enter swiftype install key here
  baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Plugins
plugins:
  fancybox: true # options: true, false
  scrollLoading: false # options: true, false
  google_analytics: UA-80620216-1 # enter the tracking ID for your Google Analytics

# Share
default: default

# Feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hueman

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/wonism/wonism.github.io.git
  branch: master

